project:
  type: website
  render:
    - "*.qmd"
  preview:
    port: 7777

website:
  title: "Null worlds"
  description: "Learn the intuition behind p-values—and conduct any statistical test—through simulation"

  site-url: "https://nullworlds.andrewheiss.com"
  favicon: "/img/favicon.png"
  image: "/img/preview.png"

  open-graph:
    image: "/img/preview.png"
    locale: en_US

  twitter-card:
    image: "/img/preview.png"
    card-style: summary_large_image

  repo-url: "https://github.com/andrewheiss/null-world-testing"
  repo-actions: [source, issue]

  navbar:
    title: "<span class='null-icon'>◎◉○</span> Null worlds"
    left:
      - href: diff-in-means.qmd
        text: Difference in means
      - href: diff-in-props.qmd
        text: Difference in proportions
      - href: one-sample-mean.qmd
        text: One-sample mean
      - href: regression.qmd
        text: Regression slope
    right:
      - icon: github
        href: "https://github.com/andrewheiss/null-world-testing"

  page-footer:
    border: false
    background: "#dddddd"
    left: |
      {{< fa brands creative-commons >}} 2026 by [Andrew Heiss](https://www.andrewheiss.com) | [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}}
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)
    center: "◎◉○"

format:
  html:
    theme:
      - zephyr
      - brand
      - css/custom.scss
